# Generated by Django 5.0.7 on 2024-07-19 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='heartparameter',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='date_added'),
        ),
    ]
