# Generated by Django 5.0.7 on 2024-08-08 02:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_remove_heartparameter_chest_pain_type_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='heartparameter',
            name='name',
        ),
    ]
