# Generated by Django 5.0.7 on 2024-08-08 02:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_remove_heartparameter_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='heartparameter',
            old_name='serum_colesterol',
            new_name='serum_cholesterol',
        ),
    ]
